INFO 2020-12-11 20:26:07,969 root : Сервер доступний. Час на сервері: 2020-12-11
INFO 2020-12-11 20:26:07,983 root : Запитувана сторінка: : http://localhost:8000/health/
INFO 2020-12-11 20:26:07,983 root : Відповідь сервера містить наступні поля:
INFO 2020-12-11 20:26:07,983 root : Ключ: date, Значення: 2020-12-11
INFO 2020-12-11 20:26:07,983 root : Ключ: current_page, Значення: http://localhost:8000/health/
INFO 2020-12-11 20:26:07,983 root : Ключ: server_info, Значення: daf7acc64db0
INFO 2020-12-11 20:26:07,983 root : Ключ: client_info, Значення: {'user_agent': 'python-requests/2.25.0', 'user_ip': '172.17.0.1', 'user_host': ''}
ERROR 2020-12-11 20:24:26,964 root : Error: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe496683b80>: Failed to establish a new connection: [Errno 111] Connection refused'))
ERROR 2020-12-11 20:25:27,024 root : Error: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe49662e490>: Failed to establish a new connection: [Errno 111] Connection refused'))
